"""esquema inicial

Revision ID: 9110f1ce44dd
Revises: 
Create Date: 2026-08-25 13:10:45.275244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9110f1ce44dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedores',
    sa.Column('codigo_axum', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('usuario_auth_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_axum'),
    sa.UniqueConstraint('usuario_auth_id')
    )
    op.create_table('objetivos_mensuales',
    sa.Column('vendedor_codigo', sa.String(length=10), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_codigo'], ['vendedores.codigo_axum'], ),
    sa.PrimaryKeyConstraint('vendedor_codigo', 'anio', 'mes')
    )
    op.create_table('ventas_totalizadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_codigo', sa.String(length=10), nullable=False),
    sa.Column('periodo_desde', sa.Date(), nullable=False),
    sa.Column('periodo_hasta', sa.Date(), nullable=False),
    sa.Column('neto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('final', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('compradores', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('comision', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cambios', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_codigo'], ['vendedores.codigo_axum'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonas',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('vendedor_codigo', sa.String(length=10), nullable=True),
    sa.Column('dia_venta', sa.String(length=120), nullable=False),
    sa.Column('dia_entrega', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_codigo'], ['vendedores.codigo_axum'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('clientes',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('zona_codigo', sa.String(length=10), nullable=True),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['zona_codigo'], ['zonas.codigo'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('novedades_zona',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_codigo', sa.String(length=20), nullable=False),
    sa.Column('vendedor_codigo', sa.String(length=10), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_codigo'], ['clientes.codigo'], ),
    sa.ForeignKeyConstraint(['vendedor_codigo'], ['vendedores.codigo_axum'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyeccion_diaria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_codigo', sa.String(length=10), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_codigo', sa.String(length=20), nullable=False),
    sa.Column('fuera_de_zona', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_codigo'], ['clientes.codigo'], ),
    sa.ForeignKeyConstraint(['vendedor_codigo'], ['vendedores.codigo_axum'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendedor_codigo', 'fecha', 'cliente_codigo', name='uq_proyeccion_dia_cliente')
    )
    op.create_table('ventas_detalle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('vendedor_codigo', sa.String(length=10), nullable=False),
    sa.Column('cliente_codigo', sa.String(length=20), nullable=True),
    sa.Column('comprobante_tipo', sa.String(length=10), nullable=True),
    sa.Column('comprobante_numero', sa.String(length=40), nullable=True),
    sa.Column('codigo_articulo', sa.String(length=20), nullable=False),
    sa.Column('descripcion_articulo', sa.String(length=200), nullable=False),
    sa.Column('familia', sa.String(length=80), nullable=True),
    sa.Column('unidades', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_codigo'], ['clientes.codigo'], ),
    sa.ForeignKeyConstraint(['vendedor_codigo'], ['vendedores.codigo_axum'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitas_reales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zona_codigo', sa.String(length=10), nullable=False),
    sa.Column('cliente_codigo', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_min', sa.String(length=20), nullable=True),
    sa.Column('hora_max', sa.String(length=20), nullable=True),
    sa.Column('tiempo_seg', sa.Integer(), nullable=False),
    sa.Column('valida', sa.Boolean(), nullable=False),
    sa.Column('larga', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_codigo'], ['clientes.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitas_reales')
    op.drop_table('ventas_detalle')
    op.drop_table('proyeccion_diaria')
    op.drop_table('novedades_zona')
    op.drop_table('clientes')
    op.drop_table('zonas')
    op.drop_table('ventas_totalizadas')
    op.drop_table('objetivos_mensuales')
    op.drop_table('vendedores')
    # ### end Alembic commands ###
