"""agregar catalogo productos_familia

Revision ID: cb61d92daf67
Revises: 9110f1ce44dd
Create Date: 2026-08-25 13:51:22.255682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb61d92daf67'
down_revision: Union[str, None] = '9110f1ce44dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_familia',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=True),
    sa.Column('familia_desc', sa.String(length=80), nullable=True),
    sa.Column('baja', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos_familia')
    # ### end Alembic commands ###
